admin:
    path: /admin
    controller: App\Controller\AdminPageController::index
index:
    path: /Team
    controller: App\Controller\TeamPageController::index
Home:
    path: /
    controller: App\Controller\HomeController::index
